DEST = ../../../obj/kernel/

include ../../../configure.mk

CFLAGS += -I../include

OBJECTS = ${DEST}baseAlloc.o
OBJECTS += ${DEST}init.o
OBJECTS += ${DEST}pageDir.o
OBJECTS += ${DEST}vmm.o

all: ${OBJECTS}
	
